package analyzer

var requiredAttributes = map[string][]string{
	"aws_instance":                      {"ami", "instance_type"},
	"aws_s3_bucket":                     {"bucket"},
	"aws_db_instance":                   {"engine", "instance_class", "allocated_storage"},
	"aws_elb":                           {"name", "listener", "availability_zones"},
	"aws_security_group":                {"name", "ingress", "egress"},
	"aws_iam_user":                      {"name"},
	"aws_iam_role":                      {"name", "assume_role_policy"},
	"aws_iam_policy":                    {"name", "policy"},
	"aws_iam_instance_profile":          {"name", "role"},
	"aws_launch_configuration":          {"name", "image_id", "instance_type"},
	"aws_autoscaling_group":             {"name", "min_size", "max_size", "launch_configuration"},
	"aws_cloudwatch_metric_alarm":       {"alarm_name", "comparison_operator", "evaluation_periods", "metric_name", "namespace", "period", "statistic", "threshold"},
	"aws_sns_topic":                     {"name"},
	"aws_sqs_queue":                     {"name"},
	"aws_dynamodb_table":                {"name", "attribute", "hash_key"},
	"aws_ecs_cluster":                   {"name"},
	"aws_ecs_task_definition":           {"family", "container_definitions"},
	"aws_ecs_service":                   {"name", "task_definition", "desired_count"},
	"aws_lambda_function":               {"filename", "function_name", "role", "handler"},
	"aws_api_gateway_rest_api":          {"name"},
	"aws_api_gateway_resource":          {"rest_api_id", "parent_id", "path_part"},
	"aws_api_gateway_method":            {"rest_api_id", "resource_id", "http_method", "authorization"},
	"aws_api_gateway_integration":       {"rest_api_id", "resource_id", "http_method", "integration_http_method", "type"},
	"aws_api_gateway_deployment":        {"rest_api_id", "stage_name"},
	"aws_route53_zone":                  {"name"},
	"aws_route53_record":                {"zone_id", "name", "type"},
	"aws_acm_certificate":               {"domain_name"},
	"aws_cloudfront_distribution":       {"origin", "enabled", "default_cache_behavior"},
	"aws_elasticache_cluster":           {"cluster_id", "engine", "node_type", "num_cache_nodes"},
	"aws_elasticache_replication_group": {"replication_group_id", "replication_group_description", "node_type", "number_cache_clusters"},
	"aws_redshift_cluster":              {"cluster_identifier", "node_type", "number_of_nodes", "database_name", "master_username", "master_password"},
	"aws_elasticsearch_domain":          {"domain_name", "elasticsearch_version"},
	"aws_kinesis_stream":                {"name", "shard_count"},
	"aws_efs_file_system":               {"creation_token"},
	"aws_kms_key":                       {"description"},
	"aws_vpc":                           {"cidr_block"},
	"aws_subnet":                        {"vpc_id", "cidr_block"},
	"aws_internet_gateway":              {"vpc_id"},
	"aws_nat_gateway":                   {"allocation_id", "subnet_id"},
	"aws_route_table":                   {"vpc_id"},
	"aws_route_table_association":       {"subnet_id", "route_table_id"},
	"aws_network_acl":                   {"vpc_id"},
	"aws_network_acl_rule":              {"network_acl_id", "rule_number", "protocol", "rule_action", "cidr_block"},
	"aws_customer_gateway":              {"bgp_asn", "ip_address", "type"},
	"aws_vpn_gateway":                   {"vpc_id"},
	"aws_vpn_connection":                {"vpn_gateway_id", "customer_gateway_id", "type"},
}
